//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace client.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ComplexNum", Namespace="http://schemas.datacontract.org/2004/07/contract")]
    [System.SerializableAttribute()]
    public partial class ComplexNum : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double imagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double realField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Desc {
            get {
                return this.DescField;
            }
            set {
                if ((object.ReferenceEquals(this.DescField, value) != true)) {
                    this.DescField = value;
                    this.RaisePropertyChanged("Desc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double imag {
            get {
                return this.imagField;
            }
            set {
                if ((this.imagField.Equals(value) != true)) {
                    this.imagField = value;
                    this.RaisePropertyChanged("imag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double real {
            get {
                return this.realField;
            }
            set {
                if ((this.realField.Equals(value) != true)) {
                    this.realField = value;
                    this.RaisePropertyChanged("real");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ICCalculator")]
    public interface ICCalculator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCalculator/addCNum", ReplyAction="http://tempuri.org/ICCalculator/addCNumResponse")]
        client.ServiceReference1.ComplexNum addCNum(client.ServiceReference1.ComplexNum n1, client.ServiceReference1.ComplexNum n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCalculator/addCNum", ReplyAction="http://tempuri.org/ICCalculator/addCNumResponse")]
        System.Threading.Tasks.Task<client.ServiceReference1.ComplexNum> addCNumAsync(client.ServiceReference1.ComplexNum n1, client.ServiceReference1.ComplexNum n2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICCalculatorChannel : client.ServiceReference1.ICCalculator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CCalculatorClient : System.ServiceModel.ClientBase<client.ServiceReference1.ICCalculator>, client.ServiceReference1.ICCalculator {
        
        public CCalculatorClient() {
        }
        
        public CCalculatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CCalculatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CCalculatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CCalculatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public client.ServiceReference1.ComplexNum addCNum(client.ServiceReference1.ComplexNum n1, client.ServiceReference1.ComplexNum n2) {
            return base.Channel.addCNum(n1, n2);
        }
        
        public System.Threading.Tasks.Task<client.ServiceReference1.ComplexNum> addCNumAsync(client.ServiceReference1.ComplexNum n1, client.ServiceReference1.ComplexNum n2) {
            return base.Channel.addCNumAsync(n1, n2);
        }
    }
}
